name: football-analysis
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - scikit-learn
    - ultralytics
    - supervision
    - opencv-python
    - numpy
    - matplotlib
    - pandas